### ISSUE TITLE
Change to support Sonoff iFan02 .. breaks speed setting to low or high when using Insteon FanLinc

### ISSUE THREAD

**Issue by brucek1642** [finity69x2/fan-control-entity-row#2]
Pressing the high button sets the speed properly then a second or so later, sets the speed to medium. A plain switch on with Insteon FanLinc always sets the speed to medium.

Removing this line restores the previous behavior for me
line 209     this.hass.callService('fan', 'turn_on', {entity_id: this._config.entity});

I also edited these line to make buttons bigger for me...  an enhancement to adjust button size would be nice

                    min-width: 65px;
		    max-width: 65px;
		    height: 65px;

	            font-size: 12px !important;

Otherwise great code thanks for sharing

**Comment by boojew** [comment]
I have ALMOST the same issue. I have a Fanlinc (via ISY integration) and selecting "High" works - but any other speed sets it to high as well... 

Edit: Actually, the behaviour is that it restores the previously set state of the fan. Removing line 209 doesnt resolve the issue for me.

**Comment by csmashe** [comment]
I am having the same issue as boojew. Lutron Casata pro fans. When i click any of the boxes it puts the fan on high. Only high and off work.

**Comment by mikerenna** [comment]
@boojew did you ever find a fix? I have isy controlled fanlinc and have same issue. Like the control so would love to get it working.

**Comment by bachulator** [comment]
Seeing same issue with my ifan02 setup.

**Comment by mim212** [comment]
Can confirm its the same issue with iFan03 running latest Tasmoda 6.7.1. Selecting High or Low from the lovelace buttons flicks to the selected speed then instantly switches to medium speed. The issue is only present when selecting the screen via the lovelace interface, not when manually selecting the speed from the detail pop-up diplay window. 

Ive analysed the traffic on mqtt and can see that the widget makes two disitct calls one for the selected speed, then one immediately after for speed '2'

Ive included a snapshot of MQTT traffic below;

`
2019-12-29 17:13:43Topic: cmnd/MainBedroomFan/FanSpeedQos: 1 2

2019-12-29 17:13:43Topic: cmnd/MainBedroomFan/FanSpeedQos: 1 3
`

I can also confirm that removing the second call for 'On' on line 209 did not effect this issue

**Comment by Fietspomp86** [comment]
I'm having (kinda) the same issue.
The state according the buttons is always "off", pressing low/medium/high buttons sets the fan to high.
Pressing the "off" button sets the fan low.
My fan is an ITHO fan, which is controlled by an ESP32 running ESPHome:
Here's my custom fan config, maybe it's of some assistance?
```
fan:
  - platform: template
    fans:
      afzuiging_badkamer:
        friendly_name: "Afzuiging badkamer"
        value_template: >
          {{ "off" if states('sensor.fanspeed') == 'Low' else "on" }}
        speed_template: "{{ states('sensor.fanspeed') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.fansendhigh
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.fansendlow
        set_speed:
          service: switch.turn_on
          data_template:
            entity_id: >
              {% set mapper = { 'Timer 1':'switch.fansendtimer1','Timer 2':'switch.fansendtimer2','Timer 3':'switch.fansendtimer3','High':'switch.fansendhigh', 'Medium':'switch.fansendmedium', 'Low':'switch.fansendlow' } %}
              {{ mapper[speed] if speed in mapper else switch.fansendlow }}
        speeds:
          - 'Low'
          - 'Medium'
          - 'High'
          - 'Timer 1'
          - 'Timer 2'
          - 'Timer 3'
```

Used to run this fan through ESPeasy and MQTT, then it worked.
But I like ESPhome so much more.
The fan control normally works BTW, when selecting the fan and selecting any speed it works fine.
